---
- hosts: network 
  user: cumulus
  become: yes
  become_method: sudo
  tasks:
#    - name: creating SSH key
#      command: ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""

    - name: copy ssh pubkey to webdir
      command: cp /root/.ssh/id_rsa.pub /var/www/html/authorized_keys    
    
    - name: Copy authorized key for Cumulus user
      copy: src=/var/www/html/authorized_keys dest=/home/cumulus/.ssh/authorized_keys

    - name: Copy authorized key for root user
      copy: src=/var/www/html/authorized_keys dest=/root/.ssh/authorized_keys

