---
# update apt sources list to enable EA features in Cumulus Linux
- hosts: network 
  become: yes
  tasks:
  - name: Copy sudoers file to each switch - has passwordless sudo for L3 python script 
    copy: src=/var/www/html/cumulus/sudoers dest=/etc/sudoers
