#l2-demo/roles/leafs/tasks/main.yml
- set_fact:
    bridges: "{{ interfaces[ansible_hostname].bridges }}"
  when: interfaces[ansible_hostname].bridges is defined

- set_fact:
    peerlink: "{{ interfaces[ansible_hostname].peerlink }}"
  when: interfaces[ansible_hostname].peerlink is defined

- set_fact:
    server_clag: "{{ interfaces[ansible_hostname].server_clag }}"
  when: interfaces[ansible_hostname].server_clag is defined

- set_fact:
    svi: "{{ addresses[ansible_hostname].svi }}"
  when: addresses[ansible_hostname].svi is defined
  
- set_fact:
    bond1: "{{ interfaces[ansible_hostname].bond1 }}"
  when: interfaces[ansible_hostname].bond1 is defined

- set_fact:
    bond2: "{{ interfaces[ansible_hostname].bond2 }}"
  when: interfaces[ansible_hostname].bond2 is defined

- set_fact:
    bond3: "{{ interfaces[ansible_hostname].bond3 }}"
  when: interfaces[ansible_hostname].bond3 is defined
  
- set_fact:
    clag_backup_ip: "{{ addresses[ansible_hostname].clag_backup_ip }}"
  when: addresses[ansible_hostname].clag_backup_ip is defined 

- set_fact:
    clag_peer_backup_ip: "{{ addresses[ansible_hostname].clag_peer_backup_ip }}"
  when: addresses[ansible_hostname].clag_peer_backup_ip is defined 

- name: configure bridges
  cl_bridge:
    name: "{{ item.name }}"
    vlan_aware: yes
    ports: "{{ item.members }}"
    stp: true
    vids: "1-10"
    pvid: "1"
  with_items: bridges
  when: bridges is defined

- name: configure peerlink
  cl_bond:
    name: "{{ item.name }}"
    slaves: "{{ item.members }}"
  with_items: peerlink
  when: peerlink is defined

- name: configure server_clag
  cl_bond:
    name: "{{ item.name }}"
    slaves: "{{ item.members }}"
    clag_id: "{{ item.clag_id }}"
  with_items: server_clag
  when: server_clag is defined

- name: configure bond1
  cl_bond:
    name: "{{ item.name }}"
    slaves: "{{ item.members }}"
    clag_id: "{{ item.clag_id }}"
  with_items: bond1
  when: bond1 is defined

- name: configure vlan 10 svi
  cl_interface:
    name: "br0.10"
    ipv4: "{{ item }}"
  with_items: svi

- name: configure clag keepalive
  cl_interface:
    name: "peerlink.4094"
    ipv4: "{{ addresses[ansible_hostname].clag_ip }}"
    clagd_enable: yes
    clagd_priority: "1000"
    clagd_sys_mac: "{{ addresses[ansible_hostname].clag_mac }}"
    clagd_peer_ip: "{{ addresses[ansible_hostname].clag_peer }}"
    clagd_args: " --vm"

- name: configure clag_backup_link_leaf
  cl_interface: 
    name: "swp6" 
    ipv4: "{{ addresses[ansible_hostname].clag_backup_ip }}/30" 
    alias_name: "clag_backup_link"

- name: configure clag backup IP
  lineinfile: dest=/etc/network/interfaces.d/peerlink.4094 regexp='' insertafter=EOF line="        clagd-backup-ip {{ addresses[ansible_hostname].clag_peer_backup_ip }}"
  with_items: clag_peer_backup_ip
  when: clag_peer_backup_ip is defined

- name: Add source /etc/network/interfaces.d/*
  lineinfile: dest=/etc/network/interfaces state=present line='source /etc/network/interfaces.d/*' insertbefore=BOF
  sudo: yes

- name: Restart networking
  service: name=networking state=restarted
  sudo: yes
