# -*- mode: ruby -*-
# vi: set ft=ruby :

groups = {
  "access" => ["mdc122ocpaccessa", "mdc122ocpaccessb"],
  "spines" => ["mdc119ocpspinea", "mdc119ocpspineb"],
  "leafs" => ["mdc119docptora", "mdc119docptorb", "rr305qocptora", "rr305qocptorb"],
  "servers" => ["server1", "server2"],
  "network:children" => ["access", "spines", "leafs"],
  "a-leafs" => ["mdc119docptora", "rr305qocptora"],
  "b-leafs" => ["mdc119docptorb", "rr305qocptorb"],
  "a-spines" => ["mdc119ocpspinea"],
  "b-spines" => ["mdc119ocpspineb"],
  "a-access" => ["mdc122ocpaccessa"],
  "b-access" => ["mdc122ocpaccessb"]
}


Vagrant.configure("2") do |config|

  cumulus_image = "CumulusCommunity/cumulus-vx"
  server_image = "ubuntu/trusty64"
  link_seed = Random.rand(999.999).to_s

  config.vm.define "mdc122ocpaccessa" do |mdc122ocpaccessa| 
    mdc122ocpaccessa.vm.box = cumulus_image
    mdc122ocpaccessa.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessa-mdc122ocpaccessb-' + link_seed, auto_config: false
    mdc122ocpaccessa.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessa-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc122ocpaccessa.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessa-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc122ocpaccessa.vm.host_name = "mdc122ocpaccessa"
    
    mdc122ocpaccessa.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    mdc122ocpaccessa.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "mdc122ocpaccessb" do |mdc122ocpaccessb|
    mdc122ocpaccessb.vm.box = cumulus_image
    mdc122ocpaccessb.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessa-mdc122ocpaccessb-' + link_seed, auto_config: false
    mdc122ocpaccessb.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessb-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc122ocpaccessb.vm.network "private_network",  virtualbox__intnet: 'mdc122ocpaccessb-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc122ocpaccessb.vm.host_name = "mdc122ocpaccessb"
    
    mdc122ocpaccessb.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    mdc122ocpaccessb.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "mdc119docptora" do |mdc119docptora| 
    mdc119docptora.vm.box = cumulus_image
    mdc119docptora.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-server1-' + link_seed, auto_config: false
    mdc119docptora.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119docptorb-' + link_seed, auto_config: false
    mdc119docptora.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119docptora.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119docptora.vm.host_name = "mdc119docptora"
    mdc119docptora.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    mdc119docptora.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end
  
  config.vm.define "mdc119docptorb" do |mdc119docptorb|
    mdc119docptorb.vm.box = cumulus_image 
    mdc119docptorb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-server1-' + link_seed, auto_config: false
    mdc119docptorb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119docptorb-' + link_seed, auto_config: false
    mdc119docptorb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119docptorb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119docptorb.vm.host_name = "mdc119docptorb"
    
    mdc119docptorb.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    mdc119docptorb.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "rr305qocptora" do |rr305qocptora| 
    rr305qocptora.vm.box = cumulus_image
    rr305qocptora.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-server2-' + link_seed, auto_config: false
    rr305qocptora.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-mdc119ocpspinea-' + link_seed, auto_config: false
    rr305qocptora.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-mdc119ocpspineb-' + link_seed, auto_config: false
    rr305qocptora.vm.host_name = "rr305qocptora"
    rr305qocptora.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    rr305qocptora.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "rr305qocptorb" do |rr305qocptorb| 
    rr305qocptorb.vm.box = cumulus_image
    rr305qocptorb.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-server2-' + link_seed, auto_config: false
    rr305qocptorb.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-mdc119ocpspinea-' + link_seed, auto_config: false
    rr305qocptorb.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-mdc119ocpspineb-' + link_seed, auto_config: false
    rr305qocptorb.vm.host_name = "rr305qocptorb"
    
    rr305qocptorb.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    rr305qocptorb.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "mdc119ocpspinea" do |mdc119ocpspinea| 
    mdc119ocpspinea.vm.box = cumulus_image
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-mdc119ocpspinea-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc122ocpaccessa-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc122ocpaccessb-' + link_seed, auto_config: false
    mdc119ocpspinea.vm.host_name = "mdc119ocpspinea"
    
    mdc119ocpspinea.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    mdc119ocpspinea.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end
  end

  config.vm.define "mdc119ocpspineb" do |mdc119ocpspineb| 
    mdc119ocpspineb.vm.box = cumulus_image
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-mdc119ocpspineb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc122ocpaccessa-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.network "private_network",  virtualbox__intnet: 'mdc119ocpspinea-mdc122ocpaccessb-' + link_seed, auto_config: false
    mdc119ocpspineb.vm.host_name = "mdc119ocpspineb"
    
    mdc119ocpspineb.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    mdc119ocpspineb.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end

  end

  config.vm.define "server1" do |server1| 
    server1.vm.box = server_image
    server1.vm.network "private_network",  virtualbox__intnet: 'mdc119docptora-server1-' + link_seed, auto_config: false
    server1.vm.network "private_network",  virtualbox__intnet: 'mdc119docptorb-server1-' + link_seed, auto_config: false
    server1.vm.host_name = "server1"
    
    server1.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvvv"
      ansible.playbook = "provision.yml"
    end

    server1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end
  
  config.vm.define "server2" do |server2| 
    server2.vm.box = server_image
    server2.vm.network "private_network",  virtualbox__intnet: 'rr305qocptora-server2-' + link_seed, auto_config: false
    server2.vm.network "private_network",  virtualbox__intnet: 'rr305qocptorb-server2-' + link_seed, auto_config: false
    server2.vm.host_name = "server2"
    
    server2.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    server2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end


end
