# -*- mode: ruby -*-
# vi: set ft=ruby :

groups = {
  "access" => ["MDC1_22_OCP_ACCESSA", "MDC1_22_OCP_ACCESSB"],
  "spines" => ["MDC1_19_OCP_SPINEA", "MDC1_19_OCP_SPINEB"],
  "leafs" => ["MDC1_19_DOCP_TORA", "MDC1_19_DOCP_TORB", "RR3-05-QOCP-TORA", "RR3-05-QOCP-TORB"],
  "servers" => ["server1", "server2"],
  "network:children" => ["access", "spines", "leafs"],
  "a-leafs" => ["MDC1_19_DOCP_TORA", "RR3_05_QOCP_TORA"],
  "b-leafs" => ["MDC1_19_DOCP_TORB", "RR3_05_QOCP_TORB"],
  "a-spines" => ["MDC1_19_OCP_SPINEA"],
  "b-spines" => ["MDC1_19_OCP_SPINEB"],
  "a-access" => ["MDC1_22_OCP_ACCESSA"],
  "b-access" => ["MDC1_22_OCP_ACCESSB"]
}


Vagrant.configure("2") do |config|

  cumulus_image = "CumulusCommunity/cumulus-vx"
  server_image = "ubuntu/trusty64"
  link_seed = Random.rand(999.999).to_s

  config.vm.define "MDC1_22_OCP_ACCESSA" do |MDC1_22_OCP_ACCESSA| 
    MDC1_22_OCP_ACCESSA.vm.box = cumulus_image
    MDC1_22_OCP_ACCESSA.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSA-MDC1_22_OCP_ACCESSB-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSA.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSA-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSA.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSA.vm.host_name = "MDC1_22_OCP_ACCESSA"
    
    MDC1_22_OCP_ACCESSA.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    MDC1_22_OCP_ACCESSA.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "MDC1_22_OCP_ACCESSB" do |MDC1_22_OCP_ACCESSB|
    MDC1_22_OCP_ACCESSB.vm.box = cumulus_image
    MDC1_22_OCP_ACCESSB.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSA-MDC1_22_OCP_ACCESSB-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSB.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSB-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSB.vm.network "private_network",  virtualbox__intnet: 'MDC1_22_OCP_ACCESSB-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_22_OCP_ACCESSB.vm.host_name = "MDC1_22_OCP_ACCESSB"
    
    MDC1_22_OCP_ACCESSB.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    MDC1_22_OCP_ACCESSB.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "MDC1_19_DOCP_TORA" do |MDC1_19_DOCP_TORA| 
    MDC1_19_DOCP_TORA.vm.box = cumulus_image
    MDC1_19_DOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-server1-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_DOCP_TORB-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORA.vm.host_name = "MDC1_19_DOCP_TORA"
    MDC1_19_DOCP_TORA.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvv"
      ansible.playbook = "provision.yml"
    end

    MDC1_19_DOCP_TORA.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end
  
  config.vm.define "MDC1_19_DOCP_TORB" do |MDC1_19_DOCP_TORB|
    MDC1_19_DOCP_TORB.vm.box = cumulus_image 
    MDC1_19_DOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-server1-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_DOCP_TORB-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_DOCP_TORB.vm.host_name = "MDC1_19_DOCP_TORB"
    
    MDC1_19_DOCP_TORB.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    MDC1_19_DOCP_TORB.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "RR3_05_QOCP_TORA" do |RR3_05_QOCP_TORA| 
    RR3_05_QOCP_TORA.vm.box = cumulus_image
    RR3_05_QOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-server2-' + link_seed, auto_config: false
    RR3_05_QOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    RR3_05_QOCP_TORA.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    RR3_05_QOCP_TORA.vm.host_name = "RR3_05_QOCP_TORA"
    RR3_05_QOCP_TORA.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    RR3_05_QOCP_TORA.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "RR3_05_QOCP_TORB" do |RR3_05_QOCP_TORB| 
    RR3_05_QOCP_TORB.vm.box = cumulus_image
    RR3_05_QOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-server2-' + link_seed, auto_config: false
    RR3_05_QOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    RR3_05_QOCP_TORB.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    RR3_05_QOCP_TORB.vm.host_name = "RR3_05_QOCP_TORB"
    
    RR3_05_QOCP_TORB.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    RR3_05_QOCP_TORB.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
    end
  end

  config.vm.define "MDC1_19_OCP_SPINEA" do |MDC1_19_OCP_SPINEA| 
    MDC1_19_OCP_SPINEA.vm.box = cumulus_image
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-MDC1_19_OCP_SPINEA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_22_OCP_ACCESSA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_22_OCP_ACCESSB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEA.vm.host_name = "MDC1_19_OCP_SPINEA"
    
    MDC1_19_OCP_SPINEA.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    MDC1_19_OCP_SPINEA.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end
  end

  config.vm.define "MDC1_19_OCP_SPINEB" do |MDC1_19_OCP_SPINEB| 
    MDC1_19_OCP_SPINEB.vm.box = cumulus_image
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-MDC1_19_OCP_SPINEB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_22_OCP_ACCESSA-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_OCP_SPINEA-MDC1_22_OCP_ACCESSB-' + link_seed, auto_config: false
    MDC1_19_OCP_SPINEB.vm.host_name = "MDC1_19_OCP_SPINEB"
    
    MDC1_19_OCP_SPINEB.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    MDC1_19_OCP_SPINEB.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc4", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc5", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc6", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc7", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc8", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc9", "allow-vms"]
    end

  end

  config.vm.define "server1" do |server1| 
    server1.vm.box = server_image
    server1.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORA-server1-' + link_seed, auto_config: false
    server1.vm.network "private_network",  virtualbox__intnet: 'MDC1_19_DOCP_TORB-server1-' + link_seed, auto_config: false
    server1.vm.host_name = "server1"
    
    server1.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      #ansible.verbose = "vvvv"
      ansible.playbook = "provision.yml"
    end

    server1.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end
  
  config.vm.define "server2" do |server2| 
    server2.vm.box = server_image
    server2.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORA-server2-' + link_seed, auto_config: false
    server2.vm.network "private_network",  virtualbox__intnet: 'RR3_05_QOCP_TORB-server2-' + link_seed, auto_config: false
    server2.vm.host_name = "server2"
    
    server2.vm.provision "ansible" do |ansible|
      ansible.groups = groups
      ansible.playbook = "provision.yml"
    end

    server2.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--nicpromisc2", "allow-vms"]
      v.customize ["modifyvm", :id, "--nicpromisc3", "allow-vms"]
    end
  end


end
